### ISSUE TITLE
Styles not displaying correctly

### ISSUE THREAD

**Issue by simonleadbetter** [wbrowar/craft-communicator#1]
This is a really useful plugin, which has saved us the effort of developing our own. Thank you!

I have noticed that there is a slight issue with the rendering of items added to the Change Log. The Unordered Lists are no showing the bullets, which is caused by a mismatch between the class name **communicator__text** declared in your templates and the class name in your CSS **communicator_text**

Hopefully, this is a simple fix for you to push.

**Comment by wbrowar** [comment]
Hey @simonleadbetter, I originally kept the list item bullets off until you hover over them, but I was using the Change Log the other day and thought it would be nice to keep them on all of the time. You're issue confirms that's the right move :)

I'll update it when I get through some other 3.2 compatibility fixes on my other plugins.

Thanks!

**Comment by wbrowar** [comment]
This is all set in 1.0.1.
