### ISSUE TITLE
Changelog with wrong date

### ISSUE THREAD

**Issue by elfacht** [wbrowar/craft-communicator#2]
The timezone is set to UTC+1 (Berlin) and when a changelog entry is submitted, the displayed date is always the day before:

<img src="https://user-images.githubusercontent.com/529443/67861761-254ff380-fb21-11e9-9ced-5e33533d5da2.jpg" width="400">
<img src="https://user-images.githubusercontent.com/529443/67861762-254ff380-fb21-11e9-9fa3-6f6aaaecf516.jpg" width="400">

**Comment by wbrowar** [comment]
This is all set in 1.0.1.
