### ISSUE TITLE
Double title in dashboard widget since Craft 3.4

### ISSUE THREAD

**Issue by jonleverrier** [wbrowar/craft-communicator#3]
Great plugin! 

Since updating to Craft 3.4+, I have come across a double title in the Dashboard widget (Email Support). This only seems to happen to the Communicator widget. 

See below:

![Screen Shot 2020-02-12 at 12 05 22](https://user-images.githubusercontent.com/2373940/74329431-17507680-4d90-11ea-888c-ad3379939977.png)

**Comment by wbrowar** [comment]
This is all set in 1.0.1.
